Importing Laibrary

In [9]:
import pandas as pd
from ydata_profiling import ProfileReport

In [10]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/bank-additional/bank-additional-full.csv",
    sep=";"
)

df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [11]:
from ydata_profiling import ProfileReport

profile = ProfileReport(
    df,
    title="Bank Marketing Data Profiling Report",
    explorative=True
)

profile.to_file("../reports/figures/profiling/bank_marketing_profile.html")

100%|██████████| 21/21 [00:00<00:00, 88.07it/s]0<00:00, 21.12it/s, Describe variable: y]
Summarize dataset: 100%|██████████| 130/130 [00:13<00:00,  9.42it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.93s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.39it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 61.93it/s]

EDA

In [12]:

# Basic Dataset Inspection
# =====================================================

# Dataset shape
print("Dataset Shape")
print(df.shape)

# -----------------------------------------------------

# First five rows
print("\nFirst Five Rows")
display(df.head())

# -----------------------------------------------------

# Last five rows
print("\nLast Five Rows")
display(df.tail())

# -----------------------------------------------------

# Column names
print("\nColumn Names")
print(df.columns.tolist())

# -----------------------------------------------------

# Data types
print("\nData Types")
display(df.dtypes)

# -----------------------------------------------------

# Dataset information
print("\nDataset Information")
df.info()

# -----------------------------------------------------

# Missing values
print("\nMissing Values")
display(df.isnull().sum())

# -----------------------------------------------------

# Duplicate rows
print("\nDuplicate Rows")
print(df.duplicated().sum())

Dataset Shape
(41188, 21)

First Five Rows

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

Last Five Rows

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

Column Names
['age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y']

Data Types

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

Missing Values

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

Duplicate Rows
12

In [13]:
# Target Variable Analysis
# =====================================================

import matplotlib.pyplot as plt
import seaborn as sns

# Count of each class
target_counts = df["y"].value_counts()

print("Target Variable Counts")
print(target_counts)

# Percentage
target_percentage = round(df["y"].value_counts(normalize=True) * 100, 2)

print("Target Variable Percentage")
print(target_percentage)

# -----------------------------------------------------
# Visualization
# -----------------------------------------------------

sns.countplot(
    data=df,
    x="y",
    hue="y",
    palette="Set2",
    legend=False
)

plt.title("Target Variable Distribution")
plt.xlabel("Subscribed to Term Deposit")
plt.ylabel("Count")

plt.show()

# -----------------------------------------------------
# Pie Chart
# -----------------------------------------------------

plt.figure(figsize=(6,6))

plt.pie(
    target_counts,
    labels=target_counts.index,
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Target Variable Percentage")

plt.show()

Target Variable Counts
y
no     36548
yes     4640
Name: count, dtype: int64
Target Variable Percentage
y
no     88.73
yes    11.27
Name: proportion, dtype: float64

C:\Users\User\AppData\Local\Temp\ipykernel_18928\3528444456.py:35: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\3528444456.py:52: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [14]:
import matplotlib.pyplot as plt
import seaborn as sns

# Target counts
target_counts = df["y"].value_counts()

print(target_counts)

# Percentage
target_percentage = round(df["y"].value_counts(normalize=True) * 100, 2)

print(target_percentage)

# ============================
# Count Plot
# ============================

plt.figure(figsize=(6,4))

plt.figure(figsize=(6,4))

sns.countplot(
    data=df,
    x="y",
    hue="y",
    palette="Set2",
    legend=False
)

plt.title("Target Variable Distribution")
plt.xlabel("Subscribed to Term Deposit")
plt.ylabel("Count")

plt.tight_layout()
plt.show()

# ============================
# Pie Chart
# ============================

plt.figure(figsize=(6,6))

plt.pie(
    target_counts,
    labels=target_counts.index,
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Target Variable Percentage")

plt.tight_layout()
plt.show()

y
no     36548
yes     4640
Name: count, dtype: int64
y
no     88.73
yes    11.27
Name: proportion, dtype: float64

C:\Users\User\AppData\Local\Temp\ipykernel_18928\490679539.py:35: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\490679539.py:53: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [15]:
# =====================================================
# Numerical Features Distribution
# =====================================================

import matplotlib.pyplot as plt
import seaborn as sns

# Numerical columns
numerical_columns = [
    "age",
    "duration",
    "campaign",
    "pdays",
    "previous",
    "emp.var.rate",
    "cons.price.idx",
    "cons.conf.idx",
    "euribor3m",
    "nr.employed"
]

# Create figure
plt.figure(figsize=(20, 15))

# Plot histogram for each numerical feature
for i, column in enumerate(numerical_columns):

    plt.subplot(4, 3, i + 1)

    sns.histplot(
        data=df,
        x=column,
        bins=30,
        kde=True,
        color="steelblue"
    )

    plt.title(f"Distribution of {column}")

plt.tight_layout()
plt.show()

C:\Users\User\AppData\Local\Temp\ipykernel_18928\3344257670.py:41: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [16]:
# =====================================================
# Categorical Features Distribution
# =====================================================

import matplotlib.pyplot as plt
import seaborn as sns

# Select categorical columns
categorical_columns = df.select_dtypes(include="object").columns

# Exclude target variable
categorical_columns = categorical_columns.drop("y")

# Plot each categorical feature
for column in categorical_columns:

    plt.figure(figsize=(8,4))

    sns.countplot(
        data=df,
        x=column,
        hue=column,
        palette="Set2",
        legend=False,
        order=df[column].value_counts().index
    )

    plt.title(f"Distribution of {column}")
    plt.xticks(rotation=45)

    plt.tight_layout()
    plt.show()

C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\User\AppData\Local\Temp\ipykernel_18928\4285357401.py:32: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()